/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoundcheckRouteImport } from './routes/soundcheck'
import { Route as ApiAddresseeRouteImport } from './routes/api/addressee'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiReflectRouteImport } from './routes/api/reflect'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTurnRouteImport } from './routes/api/turn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundcheckRoute = SoundcheckRouteImport.update({
  id: '/soundcheck',
  path: '/soundcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddresseeRoute = ApiAddresseeRouteImport.update({
  id: '/api/addressee',
  path: '/api/addressee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReflectRoute = ApiReflectRouteImport.update({
  id: '/api/reflect',
  path: '/api/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnRoute = ApiTurnRouteImport.update({
  id: '/api/turn',
  path: '/api/turn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/soundcheck': typeof SoundcheckRoute
  '/api/addressee': typeof ApiAddresseeRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/reflect': typeof ApiReflectRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/turn': typeof ApiTurnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/soundcheck': typeof SoundcheckRoute
  '/api/addressee': typeof ApiAddresseeRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/reflect': typeof ApiReflectRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/turn': typeof ApiTurnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/soundcheck': typeof SoundcheckRoute
  '/api/addressee': typeof ApiAddresseeRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/reflect': typeof ApiReflectRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/turn': typeof ApiTurnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/soundcheck'
    | '/api/addressee'
    | '/api/lead'
    | '/api/reflect'
    | '/api/speech'
    | '/api/transcribe'
    | '/api/turn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/soundcheck'
    | '/api/addressee'
    | '/api/lead'
    | '/api/reflect'
    | '/api/speech'
    | '/api/transcribe'
    | '/api/turn'
  id:
    | '__root__'
    | '/'
    | '/soundcheck'
    | '/api/addressee'
    | '/api/lead'
    | '/api/reflect'
    | '/api/speech'
    | '/api/transcribe'
    | '/api/turn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoundcheckRoute: typeof SoundcheckRoute
  ApiAddresseeRoute: typeof ApiAddresseeRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiReflectRoute: typeof ApiReflectRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTurnRoute: typeof ApiTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soundcheck': {
      id: '/soundcheck'
      path: '/soundcheck'
      fullPath: '/soundcheck'
      preLoaderRoute: typeof SoundcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/addressee': {
      id: '/api/addressee'
      path: '/api/addressee'
      fullPath: '/api/addressee'
      preLoaderRoute: typeof ApiAddresseeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reflect': {
      id: '/api/reflect'
      path: '/api/reflect'
      fullPath: '/api/reflect'
      preLoaderRoute: typeof ApiReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turn': {
      id: '/api/turn'
      path: '/api/turn'
      fullPath: '/api/turn'
      preLoaderRoute: typeof ApiTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoundcheckRoute: SoundcheckRoute,
  ApiAddresseeRoute: ApiAddresseeRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiReflectRoute: ApiReflectRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTurnRoute: ApiTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
